development:
  adapter: mysql2
  database: dmpdev	
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql2
  database: dmptest	
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8

production:
  adapter: mysql2
  database: dmp	
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8
