statusbar: false
menubar: false
toolbar:
  - bold
  - italic
  - formatselect
  - bullist
  - numlist
  - table
plugins:
  - table
  #- autoresize
height: 300
#autoresize_min_height: 50
#autoresize_max_height: 500